# Default
title: Antares Technology
logo: /assets/img/logo.jpeg
description: Servicios de electricidad, informática y telecomunicaciones 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

# Custom
excerpt_separator: <!--excerpt-->
excerpt_length: 20

# social media
facebook_url: https://www.facebook.com/AntaresTechnology.ve?mibextid=ZbWKwL
instagram_url: https://www.instagram.com/antarestechnology.ve/
whatsapp_number: 584269701138
email: antarestechnologyonline @ gmail.com

# header menu
header_menu:
- title: ¿Que hacemos?
  url: index.html
   
- title: Contáctanos
  url: contact.html

- title: Tutoriales
  url: posts.html 

- title: Portafolio
  url: portfolio.html

